plugins {
    id 'com.android.application'
}

android {
    namespace 'com.codex.google2fa'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'com.codex.google2fa'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
}
